const Estados = [
  { id: 0, nome: 'Acre', valor:'AC'},
  { id: 1, nome: 'Alagoas', valor:'AL'},
  { id: 2, nome: 'Amapá', valor:'AP'},
  { id: 3, nome: 'Amazonas', valor:'AM'},
  { id: 4, nome: 'Bahia', valor:'BA'},
  { id: 5, nome: 'Ceará', valor:'CE'},
  { id: 6, nome: 'Distrito Federal', valor:'DF'},
  { id: 7, nome: 'Espírito Santo', valor:'ES'},
  { id: 8, nome: 'Goiás', valor:'GO'},
  { id: 9, nome: 'Maranhão', valor:'MA'},
  { id: 10, nome: 'Mato Grosso', valor:'MT'},
  { id: 11, nome: 'Mato Grosso do Sul', valor:'MS'},
  { id: 12, nome: 'Minas Gerais', valor:'MG'},
  { id: 13, nome: 'Pará', valor:'PA'},
  { id: 14, nome: 'Paraíba', valor:'PB'},
  { id: 15, nome: 'Paraná', valor:'PR'},
  { id: 16, nome: 'Pernambuco', valor:'PE'},
  { id: 17, nome: 'Piauí', valor:'PI'},
  { id: 18, nome: 'Rio de Janeiro', valor:'RJ'},
  { id: 19, nome: 'Rio Grande do Norte', valor:'RN'},
  { id: 20, nome: 'Rio Grande do Sul', valor:'RS'},
  { id: 21, nome: 'Rondônia', valor:'RO'},
  { id: 22, nome: 'Roraima', valor:'RR'},
  { id: 23, nome: 'Santa Catarina', valor:'SC'},
  { id: 24, nome: 'São Paulo', valor:'SP'},
  { id: 25, nome: 'Sergipe', valor:'SE'},
  { id: 26, nome: 'Tocantins', valor:'TO'}
];